spring.application.name=codingEdu
spring.datasource.url=jdbc:postgresql://localhost:5432/codingedu
spring.datasource.username=codingedu_user
spring.datasource.password=114352
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

resend.api-key=re_EE3rU7Xi_Cu9fTj5PN69G3hKzA9t3rp7G